import { lazy, Suspense, useEffect, useMemo, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { Activity, ArrowDownToLine, ArrowRight, Bell, Box, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Database, Expand, FileText, GitBranch, LayoutDashboard, Network, Pause, Plane, Play, RotateCcw, Search, Settings2, ShieldCheck, X } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Button } from '@/components/ui/button';
import { dataset, records, summary, timeline, nodes, nodeLabels, filterRecords, exportRecords, type FlightRecord } from '@/data/flight-data';
const TelemetryScene = lazy(() => import('./telemetry-scene'));
type View = 'overview' | 'propagation' | 'explorer' | 'quality';
const navigation = [ { view: 'overview', path: '/', label: 'Overview', icon: LayoutDashboard }, { view: 'propagation', path: '/propagation', label: 'Propagation map', icon: GitBranch }, { view: 'explorer', path: '/explorer', label: 'Log explorer', icon: Database }, { view: 'quality', path: '/quality', label: 'Data validation', icon: ShieldCheck } ] as const;
const shortFamily = (family: string) => family.replace(' Log', '').replace(' Buffer', '').replace('FM ', '');
const titles = { overview: 'Mission overview', propagation: 'Fault propagation', explorer: 'Unified log explorer', quality: 'Data validation' };
function RecordDetail({ record, onClose }: { record: FlightRecord; onClose: () => void }) {
  return <div className="drawer-shade" onClick={onClose}><aside className="record-drawer" onClick={e => e.stopPropagation()}><div className="section-heading"><div><span className="eyebrow">RECORD INSPECTOR</span><h2>Event #{record.id}</h2></div><Button variant="ghost" size="icon" aria-label="Close record" onClick={onClose}><X /></Button></div><span className={`severity ${record.severity.toLowerCase()}`}>{record.severity}</span><dl className="record-fields">{[['Node', record.node], ['Timestamp', record.timestamp], ['Log family', record.log_family], ['Fault code', record.fault_code ?? '—'], ['Source file', record.filename]].map(([k,v]) => <div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><h3>Decoded message</h3><pre>{record.message}</pre><h3>Raw record</h3><pre>{JSON.stringify(record, null, 2)}</pre></aside></div>;
}
function EventTable({ rows, onSelect, compact = false }: { rows: FlightRecord[]; onSelect: (r: FlightRecord) => void; compact?: boolean }) {
  return <div className="table-scroll"><table className={`event-table ${compact ? 'compact' : ''}`}><thead><tr><th>TIMESTAMP</th><th>NODE</th><th>SEVERITY</th><th>EVENT / LOG FAMILY</th><th>FAULT CODE</th><th /></tr></thead><tbody>{rows.map(r => <tr key={r.id} onClick={() => onSelect(r)}><td className="mono">{r.timestamp.slice(11)}</td><td><span className={`node-tag ${r.node.toLowerCase()}`}>{r.node.replace('_', ' ')}</span></td><td><span className={`severity ${r.severity.toLowerCase()}`}><i />{r.severity}</span></td><td><strong>{r.fault_name || shortFamily(r.log_family)}</strong><span className="table-message">{r.message}</span></td><td className="mono">{r.fault_code ?? '—'}</td><td><Button variant="ghost" size="icon" aria-label={`Inspect record ${r.id}`} onClick={e => { e.stopPropagation(); onSelect(r); }}><ChevronRight /></Button></td></tr>)}</tbody></table>{rows.length === 0 && <div className="empty-state">No records match these filters.</div>}</div>;
}
export function FlightWorkspace({ view }: { view: View }) {
  const [hydrated, setHydrated] = useState(false);
  const [node, setNode] = useState('ALL'); const [severity, setSeverity] = useState('ALL');
  const [query, setQuery] = useState(''); const [page, setPage] = useState(0);
  const [selected, setSelected] = useState<FlightRecord | null>(null);
  const [running, setRunning] = useState(true); const [progress, setProgress] = useState(100); const [resetKey, setResetKey] = useState(0);
  const [expanded, setExpanded] = useState(false); const [notice, setNotice] = useState(false); const [help, setHelp] = useState(false);
  useEffect(() => setHydrated(true), []);
  useEffect(() => { if (!running || progress === 100) return; const id = window.setInterval(() => setProgress(p => Math.min(100, p + 1)), 120); return () => window.clearInterval(id); }, [running, progress]);
  const filtered = useMemo(() => filterRecords(query, node, severity), [query, node, severity]);
  const recent = useMemo(() => [...filtered].filter(r => r.fault_code === 6025 || r.severity === 'CRITICAL').sort((a,b) => b.timestamp.localeCompare(a.timestamp)).slice(0, 5), [filtered]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / 20));
  function setFilter(kind: 'node' | 'severity', value: string) { kind === 'node' ? setNode(value) : setSeverity(value); setPage(0); }
  const cascade = dataset.root_cause_analysis.event_cascade_steps;
  return <div className="workspace">
    <aside className="sidebar"><Link to="/" className="brand"><span className="brand-mark"><Plane /></span><span>FlightStory<span className="brand-ai">AI</span><small>FLIGHT INTELLIGENCE</small></span></Link>
      <div className="workspace-selector"><span className="workspace-symbol">H</span><div>Honeywell FMS<small>Engineering workspace</small></div><ChevronDown size={14} /></div>
      <span className="nav-caption">WORKSPACE</span><nav>{navigation.map(n => <Button key={n.view} variant="ghost" asChild className={`nav-item ${view === n.view ? 'active' : ''}`}><Link to={n.path}><n.icon /><span>{n.label}</span>{n.view === 'propagation' && <span className="nav-new">3D</span>}</Link></Button>)}</nav>
      <div className="sidebar-nodes"><span className="nav-caption">FMS NETWORK <span className="network-count">3</span></span>{nodes.map((n,i) => <div className="sidebar-node" key={n}><span className={`status-dot ${i === 2 ? 'critical' : 'success'}`} /><span>{n.replace('_',' ')}<small>{nodeLabels[n]}</small></span><span className="node-count">{records.filter(r => r.node === n).length.toLocaleString()}</span></div>)}</div>
      <div className="sidebar-bottom"><div className="dataset-state"><span className="status-dot success" /><span>Dataset connected<small>15 files · 5,257 records</small></span><ShieldCheck size={16} /></div><Button variant="ghost" className="nav-item" onClick={() => setHelp(true)}><CircleHelp /> Help & documentation</Button><div className="profile"><div className="avatar">HK</div><span>Harivignesh K<small>Workspace owner</small></span><ChevronDown size={14} /></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={13} /><span>{view === 'overview' ? 'Overview' : titles[view]}</span></div><div className="topbar-actions"><span className="environment"><span className="status-dot success" /> OFFLINE ANALYSIS</span><Button variant="ghost" size="icon" aria-label="Notifications" onClick={() => setNotice(!notice)}><Bell size={18} /></Button><div className="small-avatar">HK</div></div>{notice && <div className="notification-popover"><strong>Analysis notifications</strong><p>Fault 6025 identified on NODE C.</p><small>Imported dataset · not live telemetry</small></div>}</header>
    <main className="main-content"><div className="page-heading"><div><div className="eyebrow">FLIGHT MANAGEMENT SYSTEM <span>/</span> MULTI-NODE ANALYTICS</div><h1>{titles[view]}</h1><p>{view === 'overview' ? 'One flight. Three nodes. The complete story.' : view === 'propagation' ? 'Trace the incident across time, severity, and redundant FMS nodes.' : view === 'explorer' ? 'The complete normalized telemetry record, in one place.' : 'Source integrity and normalized record coverage.'}</p></div><div className="heading-actions"><span className="date-chip"><FileText size={14} />18 Jun 2032 <span className="mono">09:00–14:00</span></span><Button variant="outline" onClick={() => exportRecords(filtered)}><ArrowDownToLine />Export data</Button></div></div>
    <div className="dataset-ribbon"><span><span className="status-dot success" />honeywell_fms_dataset.json</span><span>15 decoded HTML files<span className="ribbon-divider" />3 redundant nodes<span className="ribbon-divider" /><ShieldCheck size={13} /> Imported source</span></div>
    {(view === 'overview' || view === 'propagation') && <>
      <div className="metrics-grid">{[{ label:'TOTAL RECORDS',value:'5,257',icon:Database,sub:'Across all three FMS nodes',foot:'15 source files',type:'neutral' },{ label:'CRITICAL EVENTS',value:summary.critical.toLocaleString(),icon:Activity,sub:'11.7% of normalized records',foot:'Requires investigation',type:'critical' },{ label:'CONNECTED NODES',value:'3 / 3',icon:Network,sub:'Primary · standby · auxiliary',foot:'All nodes represented',type:'success' },{ label:'DATA VALIDATION',value:'100%',icon:ShieldCheck,sub:'All 15 files marked PASS',foot:'Source quality report',type:'teal' }].map(m => <article className={`metric ${m.type}`} key={m.label}><div className="metric-label">{m.label}<m.icon size={17} /></div><div className="metric-value">{m.value}</div><p>{m.sub}</p><div className="metric-foot"><span className={`status-dot ${m.type}`} />{m.foot}</div></article>)}</div>
      <div className="analysis-grid"><section className={`scene-section ${expanded ? 'scene-expanded' : ''}`}><div className="section-heading"><div className="section-title"><Box size={18} /><h2>{view === 'propagation' ? '3D propagation map' : '3D event landscape'}</h2><span className="tiny-badge">WEBGL</span></div><div className="scene-header-controls"><Button size="icon" variant="ghost" title="Reset camera" aria-label="Reset camera" onClick={() => setResetKey(k => k+1)}><RotateCcw /></Button><Button size="icon" variant="ghost" title={expanded ? 'Close expanded view' : 'Expand visualization'} aria-label={expanded ? 'Close expanded view' : 'Expand visualization'} onClick={() => setExpanded(!expanded)}>{expanded ? <X /> : <Expand />}</Button></div></div>
      <div className="scene-filterbar"><div className="segmented">{['ALL', ...nodes].map(n => <Button key={n} size="sm" variant="ghost" className={node === n ? 'selected' : ''} onClick={() => setFilter('node',n)}>{n === 'ALL' ? 'All nodes' : n.replace('_',' ')}</Button>)}</div><label className="select-label"><Settings2 size={14} /><select aria-label="Scene severity" value={severity} onChange={e => setFilter('severity',e.target.value)}><option value="ALL">All severities</option><option>INFO</option><option>WARNING</option><option>CRITICAL</option></select></label></div>
      <div className="scene-viewport"><div className="scene-legend"><span><i className="legend-dot info" />Info</span><span><i className="legend-dot warning" />Warning</span><span><i className="legend-dot critical" />Critical</span></div>{hydrated && <Suspense fallback={<div className="scene-loading">Loading event landscape…</div>}><TelemetryScene node={node} severity={severity} progress={progress} running={running} resetKey={resetKey} onSelect={setSelected} propagation={view === 'propagation'} /></Suspense>}<div className="scene-caption">TIME × SEVERITY × NODE</div><div className="scene-record-count"><span className="status-dot teal" />{filtered.length.toLocaleString()} records{progress < 100 ? ' · replay' : ''}</div></div>
      <div className="scene-playback"><Button variant="ghost" size="icon" aria-label={running ? 'Pause replay' : 'Play replay'} onClick={() => { if (!running && progress === 100) setProgress(0); setRunning(!running); }}>{running ? <Pause /> : <Play />}</Button><span className="mono">09:00:00</span><input aria-label="Timeline position" type="range" min="0" max="100" value={progress} onChange={e => {setProgress(Number(e.target.value));setRunning(false);}} /><span className="mono">14:00:09</span><span className="playback-speed">1×</span></div><div className="scene-evidence">Directional links: dataset-supplied incident narrative · not independently proven causality</div></section>
      <aside className="incident-panel"><div className="section-heading"><div className="section-title"><GitBranch size={17} /><h2>Incident spotlight</h2></div><span className="tiny-badge critical">CRITICAL</span></div><div className="incident-body"><span className="eyebrow critical-text">PRIMARY FAULT · 6025</span><h3>Background service<br />identity failure</h3><div className="incident-meta"><span className="node-tag node_c">NODE C</span><span className="mono">09:09:54 AM</span></div><p>Process ID lookup failed with error 653. The source analysis links this event to repository lockouts and cross-node failover.</p><div className="incident-code">get current process id failure 653;</div><div className="incident-stats"><div><span>268</span><small>Code 6025 events</small></div><div><span>3 nodes</span><small>Cascade coverage</small></div></div><div className="incident-recovery"><Check size={15} /><span>Recovery in source narrative<small>Dual-mode consensus · 09:43:07</small></span></div><Button variant="outline" className="w-full" asChild><Link to={view === 'overview' ? '/propagation' : '/explorer'}>{view === 'overview' ? 'Explore propagation' : 'Inspect source records'}<ArrowRight /></Link></Button></div></aside></div>
      {view === 'propagation' ? <section className="cascade-section"><div className="section-heading"><div><h2>Incident chain</h2><p className="section-subtitle">Five stages from the supplied root-cause analysis</p></div><span className="tiny-badge">SOURCE NARRATIVE</span></div><div className="cascade-flow">{cascade.map((s,i) => <article className={`cascade-stage stage-${i}`} key={s.step}><div className="cascade-step">0{s.step}{i < 4 && <ArrowRight size={15} />}</div><span className="mono">{s.time}</span><h3>{s.phase}</h3><p>{s.description}</p><div className="cascade-node-list">{s.nodes.map(n => <span className={`node-tag ${n.toLowerCase()}`} key={n}>{n.replace('_',' ')}</span>)}</div></article>)}</div></section> : <div className="lower-grid"><section className="timeline-section"><div className="section-heading"><div><h2>Event activity</h2><p className="section-subtitle">10-minute intervals across the recorded window</p></div><div className="chart-legend"><span><i className="legend-dot info" />Info</span><span><i className="legend-dot warning" />Warning</span><span><i className="legend-dot critical" />Critical</span></div></div><div className="activity-chart">{hydrated && <ResponsiveContainer width="100%" height="100%"><AreaChart data={timeline} margin={{top:15,right:12,left:-24,bottom:0}}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 5" /><XAxis dataKey="time" tick={{fill:'var(--muted-foreground)',fontSize:10}} tickLine={false} axisLine={false} interval={5} /><YAxis tick={{fill:'var(--muted-foreground)',fontSize:10}} tickLine={false} axisLine={false} /><Tooltip contentStyle={{background:'var(--popover)',border:'1px solid var(--border)',borderRadius:4,color:'var(--foreground)'}} /><Area type="monotone" dataKey="INFO" stackId="1" stroke="var(--info)" fill="var(--info)" fillOpacity={.14} /><Area type="monotone" dataKey="WARNING" stackId="1" stroke="var(--warning)" fill="var(--warning)" fillOpacity={.13} /><Area type="monotone" dataKey="CRITICAL" stackId="1" stroke="var(--critical)" fill="var(--critical)" fillOpacity={.18} /></AreaChart></ResponsiveContainer>}</div></section><section className="node-health-section"><div className="section-heading"><h2>Node distribution</h2><span className="section-subtitle">Record volume</span></div>{nodes.map((n,i) => { const count = records.filter(r => r.node === n).length; return <div className="node-health-row" key={n}><span className={`node-icon node_${String.fromCharCode(97+i)}`}><Network size={15} /></span><div><strong>{n.replace('_',' ')}<span>{count.toLocaleString()}</span></strong><small>{nodeLabels[n]}</small><progress value={count} max={summary.total} /></div><span className="distribution-pct">{(count/summary.total*100).toFixed(1)}%</span></div>; })}</section></div>}
      {view === 'overview' && <section className="recent-section"><div className="section-heading"><div className="section-title"><Activity size={16} /><h2>Critical event feed</h2><span className="tiny-badge">IMPORTED</span></div><Button variant="ghost" size="sm" asChild><Link to="/explorer">View all records <ArrowRight /></Link></Button></div><EventTable rows={recent} onSelect={setSelected} compact /></section>}
    </>}
    {view === 'explorer' && <section className="explorer-section"><div className="explorer-controls"><div className="search-field"><Search size={16} /><input aria-label="Search logs" placeholder="Search messages, fault codes, or timestamps…" value={query} onChange={e => {setQuery(e.target.value);setPage(0);}} /></div><select aria-label="Filter node" value={node} onChange={e => setFilter('node',e.target.value)}><option value="ALL">All nodes</option>{nodes.map(n => <option key={n}>{n}</option>)}</select><select aria-label="Filter severity" value={severity} onChange={e => setFilter('severity',e.target.value)}><option value="ALL">All severities</option><option>INFO</option><option>WARNING</option><option>CRITICAL</option></select></div><div className="result-count">{filtered.length.toLocaleString()} matching records</div><EventTable rows={filtered.slice(page*20,page*20+20)} onSelect={setSelected} /><div className="pagination"><span>Page {page+1} of {totalPages}</span><div><Button variant="outline" size="icon" aria-label="Previous page" disabled={page === 0} onClick={() => setPage(p => p-1)}><ChevronLeft /></Button><Button variant="outline" size="icon" aria-label="Next page" disabled={page+1 >= totalPages} onClick={() => setPage(p => p+1)}><ChevronRight /></Button></div></div></section>}
    {view === 'quality' && <section className="quality-section"><div className="quality-summary"><ShieldCheck size={28} /><div><h2>15 of 15 source files passed</h2><p>Validation status supplied with the repository dataset.</p></div><span className="tiny-badge success">100% COVERAGE</span></div><div className="table-scroll"><table className="event-table"><thead><tr><th>SOURCE FILE</th><th>NODE</th><th>FAMILY</th><th>RECORDS</th><th>STATUS</th></tr></thead><tbody>{dataset.quality_stats.file_details.map(f => <tr key={f.filename}><td className="source-filename">{f.filename}</td><td><span className={`node-tag ${f.node.toLowerCase()}`}>{f.node.replace('_',' ')}</span></td><td>{shortFamily(f.family)}</td><td className="mono">{f.records_count}</td><td><span className="severity success"><Check size={12} />{f.status}</span></td></tr>)}</tbody></table></div></section>}
    <footer className="page-footer"><span><Plane size={13} />FlightStory AI <span className="footer-separator">/</span> Honeywell FMS analytics</span><span>Source snapshot · 18 June 2032 <span className="status-dot success" /></span></footer>
    </main></div>{selected && <RecordDetail record={selected} onClose={() => setSelected(null)} />}{help && <div className="drawer-shade" onClick={() => setHelp(false)}><div className="help-dialog" onClick={e => e.stopPropagation()}><div className="section-heading"><h2>About this analysis</h2><Button variant="ghost" size="icon" aria-label="Close help" onClick={() => setHelp(false)}><X /></Button></div><p>The imported FlightStory AI dataset contains 5,257 normalized FMS records from 15 decoded HTML reports. Event colors reflect each record’s assigned severity. The propagation links and incident chain come from the dataset’s root-cause narrative and are hypotheses, not independently verified causal connections.</p><p>The 3D scene encodes time horizontally, severity vertically, and node identity in depth. Drag to orbit, scroll to zoom, and select a point to inspect its source record.</p><a href="https://github.com/harivignesk/flightstory-ai" target="_blank" rel="noreferrer">View original repository <ArrowRight size={14} /></a></div></div>}
  </div>;
}
